---
title: "Introduction"
output: 
  rmarkdown::html_vignette:
    toc: true
bibliography: references.bib
link-citations: yes
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
library(spdesignR)
```

# Introduction

Efficient experimental designs have become very popular in stated preference research since their introduction in the mid 00s [@scarpa_design_2008]. 







## Existing software
Several software packages exist, for example, SAS [@kuhfeld_marketing_2007] or NGENE [@rose_ngene_2018], that can create a wide range of experimental designs ranging from full factorial to orthogonal to efficient designs. However, many of them are expensive and the code base is closed source and proprietary. In our view, this creates an unnecessary barrier for researchers that may not have access to institutional licenses or the funding necessary to buy an individual license, and it makes it more difficult for other researchers to use and build on existing research code. 

## Existing R packages
A plethora of R packages already exist to create a wide range of different experimental designs (see the [CRAN Task View](https://cran.r-project.org/web/views/ExperimentalDesign.html)), however, none of them are directly aimed at creating efficient stated preference experimental designs. For example, the [`AlgDesign`](https://cran.r-project.org/web/packages/AlgDesign/index.html) package can create full factorial and a type of D-optimal design and the [`OptimalDesign`](https://cran.r-project.org/web/packages/OptimalDesign/index.html) package calculates unblocked D-, A- and I- optimal designs. 


## Why another package?
`spdesignR` has an easy-to-use interface that people familiar with R will find intuitive to use. Users who have previously used NGENE will find the syntax somewhat familiar.

The package interfaces nicely with the [`shinySP`](#) package (under development), which allow users to easily self-host stated preference experiments using Shiny, and shares some functions with the [`cmdlR`](https://github.com/edsandorf/cmdlR) package. 

The package leverages the power of R's powerful expression parsers to enable users familiar with R to use basic mathematical operators when defining utility functions and specifying attribute levels and parameter priors. The code is fully open source and freely available to anyone under a permissive MIT license. We have done our best to document the code, its functions and workflow to allow anyone to extend and contribute to the project. If you wish to do so, please read the guidelines for [how to contribute](#) and the [detailed package documentation](#). All contributions are acknowledged and tracked using the functionalities available through [GitHub](https://github.com/). 

## Acknowledgements
The authors are grateful to members of the [Applied Choice Research Group (ACRG)](https://acrg.site) at the University of Stirling for extensively testing the package and providing feedback on the UI prior to the release of v0.1.0. 

## References
